react1-week2 HW
slastushevskyi/hyf-homework pull request #22
Opened 2023-04-19 22:27 UTC by slastushevskyi

2023-04-20 08:52 UTC, LucasIversen requested changes
Hi Nikita. Good job 👍 Just a few requested changes from here to make it perfect

2023-04-20 08:52 UTC, LucasIversen commented on react/react1/week2/vite-project/src/LifeCycleComponent.jsx
> +  useEffect(() => {
nice 👍

2023-04-20 08:52 UTC, LucasIversen commented on react/react1/week2/vite-project/src/TodoListComponent.jsx
> +  const [todoId, setTodoId] = useState(3);
Maybe we could have just used `todo.slice(-1).id + 1`, to get the id of the last todo, and then increment it by one

2023-04-20 08:52 UTC, LucasIversen commented on react/react1/week2/vite-project/src/TodoListComponent.jsx
> +            return (
Let's put this in a separate component

2023-04-21 11:41 UTC, slastushevskyi commented on react/react1/week2/vite-project/src/TodoListComponent.jsx
> +  const [todoId, setTodoId] = useState(3);
Maybe, but I was thinking another way.
I'll do it next time!

2023-04-21 18:48 UTC, slastushevskyi commented on react/react1/week2/vite-project/src/TodoListComponent.jsx
> +            return (
Did that. Thank you for review🙏

2023-04-21 18:48 UTC, merged